name: TOC Generator

on:
  push:
    branches:
      - main

jobs:

  generateTOC:

    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: technote-space/toc-generator@v4
