name: TOC Generator

on:
  push:
    branches:
      - main

jobs:

  permissions:
    contents: read
    pull-requests: write

  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
